#!/usr/bin/env python3

import os
import sys

from analyzer import Analyzer
from termcolor import colored
from helpers import *
from application import *

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets word")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    tweets = get_user_timeline(sys.argv[1])
    if (tweets == None):
        sys.exit("Screen name doesn't exist or a screen name's tweets are private")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    score = 0
    for tweet in tweets:
        score += analyzer.analyze(tweet)

    print(score)
    if score > 0.0:
        print(colored(":)", "green"))
    elif score < 0.0:
        print(colored(":(", "red"))
    else:
        print(colored(":|", "yellow"))
    return score

if __name__ == "__main__":
    main()